import "server-only";
import { createEvent, type EventAttributes } from "ics";

// Build a real .ics calendar invite for a backup-cover session.
// Returns the file contents so the client can download/attach it.
export function buildSessionInvite(opts: {
  title: string;
  facilitator: string;
  shiftLabel: string;
  durationHours?: number;
}): { ok: boolean; ics: string | null; detail: string } {
  // Next occurrence of the shift, anchored to "this week" for the demo.
  const now = new Date();
  const start = new Date(now);
  start.setDate(now.getDate() + 3); // a few days out
  start.setHours(18, 0, 0, 0);

  const event: EventAttributes = {
    title: opts.title,
    description: `Cover session — facilitator: ${opts.facilitator}. Auto-generated by BlueDot OpsPulse. ${opts.shiftLabel}.`,
    start: [
      start.getFullYear(),
      start.getMonth() + 1,
      start.getDate(),
      start.getHours(),
      start.getMinutes(),
    ],
    duration: { hours: opts.durationHours ?? 2 },
    organizer: { name: "BlueDot Course Ops", email: "ops@bluedot.org" },
    status: "CONFIRMED",
    busyStatus: "BUSY",
  };

  const { error, value } = createEvent(event);
  if (error || !value) {
    return { ok: false, ics: null, detail: "Could not build calendar invite." };
  }
  return { ok: true, ics: value, detail: "Calendar hold (.ics) generated." };
}
